version: 2.1
orbs: 
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.6
  aws-eb-cli: speakable-org/aws-eb-cli@1.0.1
jobs:
  prepare:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-cli/setup
      - checkout
      - run:
          name: Swap node versions to v16.13.2
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
            NVM_DIR="$HOME/.nvm"
            echo "export NVM_DIR=\"$HOME/.nvm\"" >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
            source $BASH_ENV
            nvm install v16
            nvm alias default v16.13.2
            node -v 
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - "./*"
       
  Frontend-Install:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
         at: /home/circleci/project
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
    
  Frontend-Build:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
         at: /home/circleci/project 
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      
  Frontend-Deploy:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
         at: /home/circleci/project 
      - run:
          name: Front-End Deployment
          command: |
            npm run frontend:deploy
  Backend-Install:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
         at: /home/circleci/project
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
  Backend-Build:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
         at: /home/circleci/project   
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
  Backend-Deploy:
    docker:
      - image: "cimg/node:14.15.5"
    steps:
      - attach_workspace:
         at: /home/circleci/project   
      - run:
          name: Back-End Deployment
          command: |
            npm run backend:deploy

workflows:
  version: 2
  build_deploy:
    jobs: 
      - prepare
      - Frontend-Install :
          requires : 
            - prepare
      - Frontend-Build :
          requires : 
            - Frontend-Install
      - Frontend-Deploy :
          requires : 
            - Frontend-Build
      - Backend-Install :
          requires : 
            - prepare
      - Backend-Build :
          requires : 
            - Backend-Install
      - Backend-Deploy :
          requires : 
            - Backend-Build